
version: '3'
services:
  
  spire-server:
    image: gcr.io/spiffe-io/spire-server:0.11.0
    hostname: spire-server
    volumes:
        - ./spire/server:/opt/spire/conf/server
        - /run/spire/sockets:/run/spire/sockets
    command: ["-config", "/opt/spire/conf/server/server.conf"]

  spire-agent:
    image: gcr.io/spiffe-io/spire-agent:0.11.0
    depends_on: ["spire-server"]
    hostname: spire-agent
    volumes:
        - ./spire/agent:/opt/spire/conf/agent
        - /run/spire/sockets:/run/spire/sockets
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]